# -*- coding: utf-8 -*-
"""resumepreparation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpBglEhQIrP_qb4PWA_FkR_AMqZHwDaa
"""

import pandas as pd
import numpy as np
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv("/content/UpdatedResumeDataSet.csv")
df.head()
#basic cleaning
# Drop duplicates or nulls
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

# Lowercase column names if needed
df.columns = [col.lower() for col in df.columns]

# Rename for clarity
df.rename(columns={'resume': 'text', 'category': 'label'}, inplace=True)


# Clean Resume Text Function
def clean_text(text):
    text = re.sub(r'http\S+', '', text)                   # Remove links
    text = re.sub(r'[^a-zA-Z\s]', '', text)               # Remove special characters
    text = re.sub(r'\s+', ' ', text)                      # Remove extra whitespace
    return text.lower()

    #Label Encoding
df['clean_text'] = df['text'].apply(clean_text)

# Add Label Encoding step
label_encoder = LabelEncoder()
df['encoded_label'] = label_encoder.fit_transform(df['label'])

tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
X = tfidf.fit_transform(df['clean_text']).toarray()
y = df['encoded_label']
#train  the mldel
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
#feature engineering
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

# Convert text to vector
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
X = tfidf.fit_transform(df['clean_text'])

# Convert labels to numbers
le = LabelEncoder()
y = le.fit_transform(df['label'])

#data preparation
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
# Assuming df has clean_text and category
texts = df['clean_text'].tolist()
labels=df['label'].tolist()

# Encode the labels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(labels)
y = to_categorical(y)  # one-hot encode for DL
vocab_size = 5000  # You can increase if needed
max_len = 300      # Max sequence length for padding

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

# Convert text to sequences
X = tokenizer.texts_to_sequences(texts)

# Pad sequences to make them same length
X = pad_sequences(X, maxlen=max_len, padding='post', truncating='post')
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42)
#depolyment
import pickle

with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)

#model building
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# Constants (you should match with your tokenizer and padded sequence setup)
vocab_size = 5000     # should match Tokenizer
embedding_dim = 128
max_length = 300      # should match pad_sequences
num_classes = y.shape[1]  # number of job categories (one-hot encoded)

# Build the model
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length),
    LSTM(128, return_sequences=True),
    Dropout(0.5),
    LSTM(64),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# Model summary
model.summary()
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=5,            # you can increase to 10–15 for better accuracy
    batch_size=32,
    verbose=1
)
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"✅ Test Accuracy: {acc:.4f}")
import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.title("Training vs Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.grid()
plt.show()

model.save("resume_classifier_model.h5")

#model compilation
 # ✅ Step: Import necessary libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dropout, Dense
import numpy as np

# Assuming num_classes is determined from your data preparation
num_classes = y_train.shape[1]

# ✅ Step: Build a sample model (for context before compilation)
model = Sequential([
    Embedding(input_dim=5000, output_dim=128, input_length=300),  # input_dim = vocab size, input_length = max length
    LSTM(128, return_sequences=True),
    Dropout(0.5),
    LSTM(64),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')  # Use the correct number of classes
])

# ✅ Step: Compile the model
model.compile(
    loss='categorical_crossentropy',  # for multi-class classification with one-hot encoded labels
    optimizer='adam',                 # adaptive optimizer
    metrics=['accuracy']              # evaluation metric
)

# ✅ Step: Print model summary (optional)
model.summary()

#model training
# ✅ Train the compiled model
history = model.fit(
    X_train, y_train,                 # your training data
    validation_data=(X_test, y_test),# your validation/test data
    epochs=10,                        # number of training cycles
    batch_size=32,                   # how many samples per training step
    verbose=1                         # display progress bar
)
# ✅ Evaluate model on test set
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"✅ Test Accuracy: {accuracy:.4f}")
import matplotlib.pyplot as plt

# Plot Accuracy
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

# Plot Loss
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Training vs Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

# ✅ Model Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Predictions
y_pred = model.predict(X_test)   # If TF-IDF features were used
y_pred_classes = np.argmax(y_pred, axis=1)   # Convert probabilities to class labels

# Decode y_test from one-hot encoding to integer labels
y_test_decoded = np.argmax(y_test, axis=1)

# Accuracy Score
print("✅ Accuracy Score:", accuracy_score(y_test_decoded, y_pred_classes))

# Classification Report
print("\n📊 Classification Report:\n", classification_report(y_test_decoded, y_pred_classes))

# Confusion Matrix
cm = confusion_matrix(y_test_decoded, y_pred_classes)
plt.figure(figsize=(10,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# from your training code (run once) streamlit model
model.save("resume_classifier_model.h5")

import pickle
with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)








!pip install streamlit pyngrok



!streamlit run app.py
from pyngrok import ngrok
public_url = ngrok.connect(8502)   # use the same port streamlit printed
print("🌍 Public URL:", public_url)

!pip install streamlit pyngrok docx2txt scikit-learn

import nest_asyncio
import threading
from pyngrok import ngrok

nest_asyncio.apply()

def run_app():
    !streamlit run app.py --server.port 8501 --server.headless true

# Kill all ngrok processes
!killall ngrok

thread = threading.Thread(target=run_app)
thread.start()

public_url = ngrok.connect(8501)
print("🌍 Public URL:", public_url)

!
